version: "3.7"

services:
  postgres:
    image: postgres
    container_name: adonis_postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=adonis_database
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redit:
    image: redis:alpine
    container_name: adonis_redis
    restart: always
    network_mode: host

volumes:
  pgdata:
    driver: local
